# Generated by Django 6.1 on 2026-08-13 14:00

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TranscriptionJob",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4, max_length=36, primary_key=True, serialize=False
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=512)),
                ("status", models.CharField(db_index=True, default="PENDING", max_length=50)),
                ("progress_percentage", models.FloatField(default=0.0)),
                ("current_step", models.CharField(default="Initialized", max_length=100)),
                ("result_json", models.TextField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Transcription Job",
                "verbose_name_plural": "Transcription Jobs",
                "db_table": "transcription_jobs",
                "ordering": ["-created_at"],
            },
        ),
    ]
