# Generated by Django 6.1 on 2026-08-15 16:00
# filename: app/db/migrations/0003_voiceprofile.py
"""Migration: Create VoiceProfile model."""

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration creating voice_profiles table and unique constraint."""

    dependencies = [
        ("db", "0002_transcription"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VoiceProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("embedding", models.JSONField(default=list)),
                ("samples_count", models.IntegerField(default=1)),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Voice Profile",
                "verbose_name_plural": "Voice Profiles",
                "db_table": "voice_profiles",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="voiceprofile",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_user_voice_profile_name"
            ),
        ),
    ]
